# general settings
name: restormer
model_type: DiffusionModel
scale: 4
num_sampling_steps: 500
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 10
nonblindsr: false
degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false
# dataset and data loader settings

datasets:
  train:
    name: DF2K
    type: BlindImageDataset
    dataroot_gt: /training/dataset/path/
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    scale: 4
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /Set5/dataset/path/HR/
    dataroot_lq: /Set5/dataset/path/LR/
    io_backend:
      type: disk

# network structures
network_g:
  type: Restormer2
  inp_channels: 3
  out_channels: 6
  dim: 48
  num_blocks: [2, 3, 6 ,8]
  num_refinement_blocks: 2
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  scale: 4
  kernel_size: 21

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~ 
  
grad_opt:
  alpha: 1
  lamda: 0

cri_k:
  loss_weight: 1

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 400000, 500000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
  detail_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  structure_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:  
  val_freq: !!float 1e5
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      
    lpips:
      type: calculate_lpips
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 500000
