# GENERATE TIME: Wed Aug 16 13:18:34 2023
# CMD:
# basicsr/train.py -opt=setting2.yml

 # GENERATE TIME: Mon Dec 20 21:53:47 2021
# CMD:
# basicsr/train.py -opt=options/train/DC/train_DCv1_x4_5G10B_bs16_setting1.yml

# general settings
name: BlindDiff_df2k_setting2
model_type: DiffusionModel
scale: 4
num_sampling_steps: 500
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 10
nonblindsr: false
degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.6
  sig_max: 5
  rate_iso: 0
  random_disturb: true
# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: BlindImageDataset
    dataroot_gt: /opt/data/private/wyx/DIV2K+Flickr2K/
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    scale: 4
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 10
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5G8
    type: PairedImageDataset
    dataroot_gt: /opt/data/private/wyx/imagenet_val_1k_x4g8/miniHR/
    dataroot_lq: /opt/data/private/wyx/imagenet_val_1k_x4g8/miniLR/
    io_backend:
      type: disk

# network structures
network_g:
  type: BlindDiff
  inp_channels: 3
  out_channels: 6
  dim: 48
  num_blocks: [2, 3, 6 ,8]
  num_refinement_blocks: 2
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  scale: 4
  kernel_size: 21

# path
path:
  pretrain_network_g: pretrained_models/blinddiff_df2k_setting1.pth
  strict_load_g: true
  resume_state: ~
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 400000, 500000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
    
  detail_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  structure_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:  
  val_freq: !!float 5e4
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      
    lpips:
      type: calculate_lpips
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
t_params:
  backend: nccl
  port: 29500
